### ISSUE TITLE
Timeout error when send Multiple Messages to expo backend

### ISSUE THREAD

**Issue by vuvantoan95** [rdrop/exponent-server-sdk-elixir#2]
`%HTTPoison.Error{id: nil, reason: :timeout}
//////////////////////////////////////////////////////////////////////////
03:38:07.879 [error] Process #PID<0.11794.0> on node :"pancake_v2@web-app-7" raised an exception
** (HTTPoison.Error) :timeout
    (exponent_server_sdk) lib/exponent_server_sdk/push_notification.ex:19: ExponentServerSdk.PushNotification.request!/5
    (exponent_server_sdk) lib/exponent_server_sdk/push_notification.ex:46: ExponentServerSdk.PushNotification.push_list/1`

**Comment by rdrop** [comment]
I'll look into this next week and update
